### ISSUE TITLE
[Generate template]

### ISSUE THREAD

**Issue by gladshop** [fahadmaq007/report-generator#1]
Hi bro,

Could you help me how to generate template and insert variable? I can't create template as your template. Does you using any tools?

Thank you.

**Comment by fahadmaq007** [comment]
Hello there,

Glad to hear from you.

No, there is no other tool that is required to create the template, it's the standard MS Word function. May be you are not following the right syntax in the Word Template. Please check the following snapshot - if you are not seeing MERGEFIELD in the template, press Alt+F9 (in Macbook & whatever is right key in your OS) & add this expression Address: { MERGEFIELD $address1} - if that's not working just copy it from the Demo Template. 

<img width="851" alt="Screen Shot 2021-05-26 at 1 08 56 PM" src="https://user-images.githubusercontent.com/11307582/119621348-a23d6f00-be23-11eb-9ad7-1b7721fabe80.png">
